# -*- coding: utf-8 -*-
"""HRA_Standing_vs_Walking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NxiH7YNSzFcnW24cgsfW9hkr4G0stXg

**Human Activity Recognition**

 Activities: Standing and Walking

 Sensors: Accelerometer + Gyroscope

**Problem Statement:**

The objective of this project is to develop a machine learning model that can recognize and classify human activities based on sensor data from a mobile device. Using accelerometer and gyroscope data collected at King Saud University, this project aims to:
 - Analyze and preprocess the data to make it suitable for machine learning.
 - Build and evaluate machine learning models to classify activities as either "standing" or "walking" with high accuracy.
 - Further action-Optimize the model to ensure robust performance, even with limited and noisy data, for potential real-time application in mobile devices.
"""

# Column     Data Type                Description
# accX    float           Acceleration along the X-axis in m/s², measured by the mobile phone’s accelerometer sensor.
# accY    float           Acceleration along the Y-axis in m/s², measured by the mobile phone’s accelerometer sensor.
# accZ    float           Acceleration along the Z-axis in m/s², measured by the mobile phone’s accelerometer sensor.
# gyroX   float           Angular velocity around the X-axis in rad/s, measured by the mobile phone’s gyroscope sensor.
# gyroY   float           Angular velocity around the Y-axis in rad/s, measured by the mobile phone’s gyroscope sensor.
# gyroZ   float           Angular velocity around the Z-axis in rad/s, measured by the mobile phone’s gyroscope sensor.
# Timestamp time          Timestamp of the recorded sensor data in HH
# .S format,              indicating the time the measurement was taken.
# Activity  integer       Label for the activity being performed. 0 represents standing (stop), and 1 represents walking.

# Step 1: Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: Loading dataset
df = pd.read_csv("HRA_Standing_vs_Walking_Dataset.csv")
df

"""**Pre-processing**"""

print("Shape of the dataset :",df.shape)

print("Columns: ", df.columns)

print("Data Types: \n", df.dtypes)

print("Missing value check:")
df.isnull().sum()

print("Checking duplicates:")
df.duplicated().sum()

print("Activity distribution:")
print(df['Activity'].value_counts())

print("\nActivity percentage:")
print(df['Activity'].value_counts(normalize=True) * 100)

print("\nUnique Activity values:")
print(df['Activity'].unique())

sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ'
]

print(df[sensor_cols].describe().T)

# Converting time to seconds:
def timestamp_to_seconds(t):
    minutes, seconds = str(t).strip().split(':')
    return int(minutes) * 60 + float(seconds)

df['time_seconds'] = df['timestamp'].apply(timestamp_to_seconds)

def check_timestamp_format(t):
    try:
        minutes, seconds = str(t).strip().split(':')
        float(minutes)
        float(seconds)
        return True
    except:
        return False

timestamp_valid = df['timestamp'].apply(check_timestamp_format)

print("Valid timestamps:", timestamp_valid.sum())
print("Invalid timestamps:", (~timestamp_valid).sum())

print("\nInvalid timestamp values:")
print(df.loc[~timestamp_valid, 'timestamp'].unique())

def check_timestamp_format(t):          # Checking incorrect Timestamp
    try:
        minutes, seconds = str(t).strip().split(':')
        int(minutes)
        float(seconds)
        return True
    except:
        return False

invalid_mask = ~df['timestamp'].apply(check_timestamp_format)

print(df.loc[invalid_mask, ['timestamp', 'Activity']])

invalid_idx = df.index[invalid_mask]      # retriving invalid timestamp row

print("Invalid rows:", invalid_idx.tolist())

df.loc[invalid_idx, 'timestamp'] = '05:48.0'

print(df.loc[invalid_idx, 'timestamp'])

invalid_mask = ~df['timestamp'].apply(check_timestamp_format)

print("Invalid timestamps remaining:", invalid_mask.sum())

if invalid_mask.sum() > 0:
    print(df.loc[invalid_mask, 'timestamp'])

def timestamp_to_seconds(t):
    minutes, seconds = str(t).strip().split(':')
    return int(minutes) * 60 + float(seconds)

df['time_seconds'] = df['timestamp'].apply(timestamp_to_seconds)

print(df[['timestamp', 'time_seconds']].head())

df['time_diff'] = df['time_seconds'].diff()

print("Time difference statistics:")
print(df['time_diff'].describe())

print("\nMost common intervals:")
print(df['time_diff'].round(3).value_counts().head(15))

df['timestamp_reset'] = df['time_diff'] < 0

print("Number of timestamp resets:",
      df['timestamp_reset'].sum())

df['recording_id'] = df['timestamp_reset'].cumsum()

print("Number of recordings:",
      df['recording_id'].nunique())

print("\nSamples per recording:")
print(df.groupby('recording_id').size())

#Checking Activity distribution by recording
print("\nActivity distribution by recording:")

activity_recording = pd.crosstab(
    df['recording_id'],
    df['Activity']
)

display(activity_recording)

# Missing value checking
print("Missing values:")
print(df.isnull().sum())

# Checking intervals where the timestamps are reseted
reset_indices = df.index[df['timestamp_reset']]

print("Timestamp reset locations:\n")

for idx in reset_indices:
    print("=" * 60)
    print("Reset index:", idx)

    display(
        df.loc[
            max(0, idx-2):idx+2,
            ['timestamp', 'time_seconds',
             'time_diff', 'Activity']
        ]
    )

large_gaps = df[df['time_diff'] > 1]

print("Number of gaps > 1 second:", len(large_gaps))

display(
    large_gaps[
        ['timestamp', 'time_seconds',
         'time_diff', 'Activity', 'recording_id']
    ]
)

# Show distribution of gaps
gap_values = df.loc[df['time_diff'] > 1, 'time_diff']

print("Number of gaps > 1 sec:", len(gap_values))

print("\nGap statistics:")
print(gap_values.describe())

print("\nGaps grouped by recording:")
print(
    df.loc[df['time_diff'] > 1]
      .groupby('recording_id')
      .size()
)

print("\nAll gaps:")
display(
    df.loc[
        df['time_diff'] > 1,
        ['timestamp', 'time_seconds',
         'time_diff', 'Activity', 'recording_id']
    ]
)

df['large_gap'] = df['time_diff'] > 1.0

print("Large gaps:", df['large_gap'].sum())

# Change in activity
df['activity_change'] = df['Activity'].ne(
    df['Activity'].shift()
)

print("Activity changes:",
      df['activity_change'].sum())

print(
    df.loc[df['activity_change'],
           ['timestamp', 'time_seconds',
            'time_diff', 'Activity']]
    .head(30)
)

# finding large gap between intervals
df['large_gap'] = df['time_diff'] > 1.0

df['activity_change'] = df['Activity'].ne(
    df['Activity'].shift()
)

print("Large gaps:", df['large_gap'].sum())
print("Activity changes:", df['activity_change'].sum())

print("\nActivity-change locations:")
display(
    df.loc[
        df['activity_change'],
        ['timestamp', 'time_seconds',
         'time_diff', 'Activity']
    ].head(30)
)

# Show all large gaps
large_gaps = df[df['time_diff'] > 1.0].copy()

display(
    large_gaps[
        ['timestamp', 'time_seconds', 'time_diff', 'Activity']
    ].to_string()
)

# gap summary
gap_summary = df.loc[df['time_diff'] > 1.0,
                     ['time_diff', 'Activity']].copy()

print("Number of gaps > 1 sec:", len(gap_summary))

print("\nGap duration statistics:")
display(gap_summary['time_diff'].describe())

display(
    df.loc[df['time_diff'] > 1.0,
           ['timestamp', 'time_seconds', 'time_diff', 'Activity']]
    .sort_values('time_diff', ascending=False)
    .head(30)
)

# checking for the segment breaks to find the actucal samples of the intervals
# and activity distributions

df['segment_break'] = (
    (df['time_diff'].abs() > 1.0)
)

df['segment_id'] = df['segment_break'].cumsum()

print("Number of segments:", df['segment_id'].nunique())

print("\nSamples per segment:")
display(
    df.groupby('segment_id')
      .agg(
          samples=('Activity', 'size'),
          activity_0=('Activity', lambda x: (x == 0).sum()),
          activity_1=('Activity', lambda x: (x == 1).sum())
      )
)

activity_0 = df[df['Activity'] == 0].copy()

print("Total Activity 0 samples:", len(activity_0))

print("\nActivity 0 index range:")
print(activity_0.index.min(), "to", activity_0.index.max())

print("\nActivity 0 by segment:")
display(
    activity_0.groupby('segment_id')
    .size()
    .reset_index(name='samples')
)

# Detailed summary of Activity 0 segments

print("\nDetailed Activity 0 segments:")

display(
    df[df['Activity'] == 0]
    .groupby('segment_id')
    .agg(
        start_index=('Activity', lambda x: x.index.min()),
        end_index=('Activity', lambda x: x.index.max()),
        samples=('Activity', 'size'),
        start_time=('time_seconds', 'min'),
        end_time=('time_seconds', 'max')
    )
)

# So all 571 Activity 0 samples belong to one continuous activity period.

# Inside this period, the label changes repeatedly between 0 and 1 according to your earlier output,
# but the timestamp remains continuous at approximately 10 Hz. Therefore, those Activity 0 portions are not separate recordings.
# And this explains your severe class imbalance:

# Activity 0 = 571 samples
# Activity 1 = 31,420 samples

# approximately 1.8% vs 98.2%.

# Activity sequence from the region containing Activity 0

activity_region = df.loc[20923:21951,
                         ['timestamp', 'time_seconds', 'time_diff', 'Activity']].copy()

display(activity_region)

# Finding continuous runs of the same activity

region = df.loc[20923:21951, ['time_seconds', 'Activity']].copy()

region['activity_change'] = (
    region['Activity'] != region['Activity'].shift()
)

region['activity_run'] = region['activity_change'].cumsum()

runs = (
    region.groupby('activity_run')
    .agg(
        activity=('Activity', 'first'),
        start_index=('Activity', lambda x: x.index.min()),
        end_index=('Activity', lambda x: x.index.max()),
        samples=('Activity', 'size'),
        start_time=('time_seconds', 'first'),
        end_time=('time_seconds', 'last')
    )
    .reset_index(drop=True)
)

display(runs)

# Activity 0 is not one single uninterrupted episode. It consists of 10 separate Activity-0 runs, embedded within Activity-1 runs.
# So the shortest Activity-0 episode is ~2.7 seconds, while the longest is ~15.2 seconds.

# Activity 0 occurs within one continuous timestamp region, but it contains 10 separate activity episodes.

# Checking exact duplicate rows
duplicate_count = df.duplicated().sum()

print("Exact duplicate rows:", duplicate_count)

sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ'
]

print(
    "Duplicate sensor rows:",
    df.duplicated(subset=sensor_cols).sum()
)

# Checking missing values
print("Missing values:")
display(df.isnull().sum())

df['time_diff'] = df['time_diff'].fillna(0)

print("Exact duplicate rows:", df.duplicated().sum())

sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ'
]

print(
    "Duplicate sensor rows:",
    df.duplicated(subset=sensor_cols).sum()
)

sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ'
]

dup_sensor = df[
    df.duplicated(subset=sensor_cols, keep=False)
].copy()

print("Rows involved in duplicate sensor readings:", len(dup_sensor))

display(
    dup_sensor[
        sensor_cols + ['timestamp', 'time_seconds', 'Activity']
    ].sort_values(sensor_cols).head(30)
)

conflicting_duplicates = (
    dup_sensor.groupby(sensor_cols)['Activity']
    .nunique()
)

print(
    "Sensor patterns having multiple Activity labels:",
    (conflicting_duplicates > 1).sum()
)

dup_sensor['row_gap'] = dup_sensor.index.to_series().diff()

print("Row-gap statistics for duplicate sensor readings:")
display(dup_sensor['row_gap'].describe())

# Check exact duplicates based on the actual data columns
data_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ',
    'timestamp',
    'Activity'
]

print(
    "Duplicate rows based on sensor + timestamp + Activity:",
    df.duplicated(subset=data_cols).sum()
)

dup = df[df.duplicated(subset=data_cols, keep=False)].copy()

dup['original_index'] = (
    dup.groupby(data_cols, sort=False)
       .cumcount()
)

display(
    dup[data_cols + ['original_index']]
    .head(20)
)

duplicate_indices = df[
    df.duplicated(subset=data_cols, keep=False)
].index

print("Duplicate index range:")
print(duplicate_indices.min(), duplicate_indices.max())

print("\nNumber of duplicate rows:", len(duplicate_indices))

# Compare the two suspected duplicated blocks

block1 = df.loc[19223:19543, [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ',
    'timestamp', 'Activity'
]].reset_index(drop=True)

block2 = df.loc[19555:19687, [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ',
    'timestamp', 'Activity'
]].reset_index(drop=True)

print("Block 1 shape:", block1.shape)
print("Block 2 shape:", block2.shape)

data_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ',
    'timestamp', 'Activity'
]

dup_check = df[df.duplicated(
    subset=data_cols,
    keep=False
)].copy()

dup_check['duplicate_group'] = (
    dup_check.groupby(data_cols, sort=False)
             .ngroup()
)

print("Unique duplicated patterns:",
      dup_check['duplicate_group'].nunique())

display(
    dup_check.groupby('duplicate_group')
    .size()
    .value_counts()
    .sort_index()
)

data_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ',
    'timestamp', 'Activity'
]

before = len(df)

df = df.drop_duplicates(
    subset=data_cols,
    keep='first'
).reset_index(drop=True)

after = len(df)

print("Rows before:", before)
print("Rows removed:", before - after)
print("Rows after:", after)

# Remaining duplicate records

df['time_diff'] = df['time_seconds'].diff().fillna(0)
print("Remaining duplicate records:",
      df.duplicated(subset=data_cols).sum())

print("Missing values:")
display(df.isnull().sum())

"""**Exploratory Data Analysis**"""

# EDA — Step 1: Activity distribution

print("Activity counts:")
print(df['Activity'].value_counts())

print("\nActivity percentages:")
print(df['Activity'].value_counts(normalize=True) * 100)

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Activity')
plt.title('Activity Distribution')
plt.xlabel('Activity')
plt.ylabel('Number of Samples')
plt.show()

# Activity over time
plt.figure(figsize=(16, 5))

plt.plot(
    df['time_seconds'],
    df['Activity'],
    drawstyle='steps-post'
)

plt.xlabel('Time (seconds)')
plt.ylabel('Activity')
plt.title('Activity Distribution Over Time')
plt.yticks([0, 1])
plt.grid(True, alpha=0.3)

plt.show()

# Activity 1 dominates almost the entire timeline.
# Activity 0 is concentrated in a relatively short portion around roughly 350–450 seconds.
# There are also a few very short Activity 0 intervals around ~350–450 s rather than one single continuous activity.
# The large jump in the timeline is related to the timestamp discontinuities we found earlier, so we should not interpret the horizontal distance as continuous physical activity.
# This confirms that your imbalance isn't just a random class-count problem — the minority activity is temporally concentrated.

# Sensor distributions by Activity
sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ'
]

fig, axes = plt.subplots(2, 3, figsize=(16, 8))

for ax, col in zip(axes.flatten(), sensor_cols):
    sns.boxplot(
        data=df,
        x='Activity',
        y=col,
        ax=ax
    )
    ax.set_title(f'{col} by Activity')
    ax.set_xlabel('Activity')

plt.tight_layout()
plt.show()

# 2. Gyroscope features

# gyroX, gyroY, and gyroZ have substantial overlap between the two activities.
# However, Activity 1 generally has a wider spread, particularly for gyroY and gyroZ.

# Compare sensor means and variability
summary = df.groupby('Activity')[sensor_cols].agg(['mean', 'std', 'min', 'max'])

display(summary)

#  Correlation between six sensors
corr = df[sensor_cols].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(
    corr,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    center=0
)

plt.title('Correlation Between Sensor Features')
plt.show()

# There is no strong linear redundancy among your six sensor axes.
# We should NOT remove any sensor axis based on correlation.
# Each axis may contain different movement/orientation information.

# Acceleration magnitude
# Gyroscope magnitude

df['acc_mag'] = np.sqrt(
    df['accX']**2 +
    df['accY']**2 +
    df['accZ']**2
)

df['gyro_mag'] = np.sqrt(
    df['gyroX']**2 +
    df['gyroY']**2 +
    df['gyroZ']**2
)

print(df[['acc_mag', 'gyro_mag']].describe())

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sns.boxplot(
    data=df,
    x='Activity',
    y='acc_mag',
    ax=axes[0]
)
axes[0].set_title('Acceleration Magnitude by Activity')

sns.boxplot(
    data=df,
    x='Activity',
    y='gyro_mag',
    ax=axes[1]
)
axes[1].set_title('Gyroscope Magnitude by Activity')

plt.tight_layout()
plt.show()

# Acceleration magnitude — very useful

# Activity 0 is tightly concentrated around ~9.8 m/s², while Activity 1 has a much wider distribution.

# That makes physical sense: during a relatively stationary activity, acceleration magnitude stays close to gravity (~9.8 m/s²),
# whereas walking introduces much more variation. So acc_mag looks like a strong candidate feature.

# 2. Gyroscope magnitude — useful, but weaker

# The distributions overlap considerably, but Activity 1 has a somewhat higher median and many more high-value observations.

# So gyro_mag may provide additional information, but it doesn't separate the activities as clearly as acc_mag.

# visualize actual sensor signals

start_time = 340
end_time = 455

plot_df = df[
    (df['time_seconds'] >= start_time) &
    (df['time_seconds'] <= end_time)
]

fig, axes = plt.subplots(2, 1, figsize=(16, 9), sharex=True)

# Acceleration magnitude
axes[0].plot(
    plot_df['time_seconds'],
    plot_df['acc_mag']
)
axes[0].set_title('Acceleration Magnitude During Activity Transitions')
axes[0].set_ylabel('Acceleration Magnitude')
axes[0].grid(True, alpha=0.3)

# Gyroscope magnitude
axes[1].plot(
    plot_df['time_seconds'],
    plot_df['gyro_mag']
)
axes[1].set_title('Gyroscope Magnitude During Activity Transitions')
axes[1].set_xlabel('Time (seconds)')
axes[1].set_ylabel('Gyroscope Magnitude')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

### Acceleration magnitude
# There are relatively stable regions around 9.5–10 m/s².
# Other regions show large and rapid fluctuations, going roughly from 6 to 15+ m/s².
# These fluctuations are much more informative for activity recognition than a single acceleration reading.

### Gyroscope magnitude
# There are periods where the magnitude stays close to zero.
# Other periods contain frequent spikes, particularly around 360–430 seconds.
# This suggests gyroscope variation over time may help distinguish activities even though its raw correlation with the activity label is weak.

# activity-wise variability

variability = df.groupby('Activity')[sensor_cols + ['acc_mag', 'gyro_mag']].std()

display(variability.T)

# feature engineering

df['activity_change'] = df['Activity'].ne(df['Activity'].shift())

df['run_id'] = df['activity_change'].cumsum()

activity_runs = (
    df.groupby(['run_id', 'Activity'])
      .agg(
          start_time=('time_seconds', 'min'),
          end_time=('time_seconds', 'max'),
          samples=('Activity', 'size')
      )
      .reset_index()
)

activity_runs['duration_sec'] = (
    activity_runs['end_time'] - activity_runs['start_time']
)

display(activity_runs)

# a 2-second window is a sensible starting point.

# Create valid continuous segments
# Recalculate time difference after all preprocessing
df['time_diff'] = df['time_seconds'].diff()

# A new continuous segment starts when:
# 1. timestamp has a large gap
# 2. timestamp goes backward/reset
# 3. activity changes

segment_break = (
    (df['time_diff'].abs() > 1) |
    (df['time_diff'] < 0) |
    (df['Activity'] != df['Activity'].shift())
)

df['segment_id'] = segment_break.cumsum()

print("Number of valid segments:", df['segment_id'].nunique())

segment_summary = (
    df.groupby(['segment_id', 'Activity'])
      .agg(
          samples=('Activity', 'size'),
          start_time=('time_seconds', 'first'),
          end_time=('time_seconds', 'last')
      )
      .reset_index()
)

segment_summary['duration_sec'] = (
    segment_summary['end_time'] -
    segment_summary['start_time']
)

display(segment_summary)

window_size = 20  # 2 seconds at 10 Hz

segment_stats = (
    df.groupby(['segment_id', 'Activity'])
      .size()
      .reset_index(name='samples')
)

segment_stats['can_make_2sec_window'] = (
    segment_stats['samples'] >= window_size
)

print("Segments by activity:")
display(
    segment_stats.groupby('Activity')['segment_id']
    .count()
    .rename('segments')
)

print("\nSegments capable of producing at least one 2-sec window:")
display(
    segment_stats.groupby('Activity')['can_make_2sec_window']
    .sum()
    .rename('segments_with_2sec_window')
)

print("\nMinimum segment size:")
display(
    segment_stats.groupby('Activity')['samples']
    .agg(['min', 'median', 'max'])
)

"""**Window Generation**"""



# CREATE 2-SECOND WINDOWS

WINDOW_SIZE = 20       # 20 samples = 2 seconds at 10 Hz
STEP_SIZE = 10         # 50% overlap

sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ'
]

windows = []
window_id = 0

# Process each continuous segment separately
for segment_id, segment in df.groupby('segment_id'):

    segment = segment.reset_index(drop=True)

    # Create overlapping windows
    for start in range(0, len(segment) - WINDOW_SIZE + 1, STEP_SIZE):

        end = start + WINDOW_SIZE

        window = segment.iloc[start:end]

        # Activity label of the window
        # Since segment_id was created at activity changes,
        # every row in this window has the same Activity.
        activity = window['Activity'].iloc[0]

        windows.append({
            'window_id': window_id,
            'segment_id': segment_id,
            'Activity': activity,
            'start_time': window['time_seconds'].iloc[0],
            'end_time': window['time_seconds'].iloc[-1],
            'samples': len(window),
            'data': window[sensor_cols].values
        })

        window_id += 1


# Convert to DataFrame
windows_df = pd.DataFrame(windows)

print("Total windows:", len(windows_df))

print("\nWindows by Activity:")
print(windows_df['Activity'].value_counts().sort_index())

print("\nWindow size distribution:")
print(windows_df['samples'].value_counts())

display(windows_df.head())

# VALIDATE THE WINDOWS

print("Total windows:", len(windows_df))

print("\nActivity distribution:")
print(windows_df['Activity'].value_counts())

print("\nActivity percentage:")
print(
    windows_df['Activity']
    .value_counts(normalize=True)
    .mul(100)
)

print("\nIncorrect window sizes:")
print(
    windows_df[
        windows_df['samples'] != WINDOW_SIZE
    ].shape[0]
)

print("\nNumber of segments used:")
print(windows_df['segment_id'].nunique())

# STEP: ADD MAGNITUDE SIGNALS TO EACH WINDOW

feature_sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ',
    'acc_mag', 'gyro_mag'
]

windows = []
window_id = 0

for segment_id, segment in df.groupby('segment_id'):

    segment = segment.reset_index(drop=True)

    for start in range(
        0,
        len(segment) - WINDOW_SIZE + 1,
        STEP_SIZE
    ):

        end = start + WINDOW_SIZE
        window = segment.iloc[start:end]

        windows.append({
            'window_id': window_id,
            'segment_id': segment_id,
            'Activity': window['Activity'].iloc[0],
            'start_time': window['time_seconds'].iloc[0],
            'end_time': window['time_seconds'].iloc[-1],
            'samples': len(window),
            'data': window[feature_sensor_cols].values
        })

        window_id += 1

windows_df = pd.DataFrame(windows)

print("Total windows:", len(windows_df))
print("\nWindow distribution:")
print(windows_df['Activity'].value_counts().sort_index())

print("\nData shape of first window:")
print(windows_df.loc[0, 'data'].shape)

# STEP: ADD MAGNITUDE SIGNALS TO EACH WINDOW

feature_sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ',
    'acc_mag', 'gyro_mag'
]

windows = []
window_id = 0

for segment_id, segment in df.groupby('segment_id'):

    segment = segment.reset_index(drop=True)

    for start in range(
        0,
        len(segment) - WINDOW_SIZE + 1,
        STEP_SIZE
    ):

        end = start + WINDOW_SIZE
        window = segment.iloc[start:end]

        windows.append({
            'window_id': window_id,
            'segment_id': segment_id,
            'Activity': window['Activity'].iloc[0],
            'start_time': window['time_seconds'].iloc[0],
            'end_time': window['time_seconds'].iloc[-1],
            'samples': len(window),
            'data': window[feature_sensor_cols].values
        })

        window_id += 1

windows_df = pd.DataFrame(windows)

print("Total windows:", len(windows_df))
print("\nWindow distribution:")
print(windows_df['Activity'].value_counts().sort_index())

print("\nData shape of first window:")
print(windows_df.loc[0, 'data'].shape)

# STEP: FEATURE EXTRACTION

import numpy as np
import pandas as pd

feature_sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ',
    'acc_mag', 'gyro_mag'
]

feature_rows = []

for _, row in windows_df.iterrows():

    data = row['data']

    features = {
        'window_id': row['window_id'],
        'segment_id': row['segment_id'],
        'Activity': row['Activity']
    }

    # Extract statistical features for each sensor
    for i, sensor in enumerate(feature_sensor_cols):

        signal = data[:, i]

        features[f'{sensor}_mean'] = np.mean(signal)
        features[f'{sensor}_std'] = np.std(signal)
        features[f'{sensor}_min'] = np.min(signal)
        features[f'{sensor}_max'] = np.max(signal)
        features[f'{sensor}_range'] = np.max(signal) - np.min(signal)
        features[f'{sensor}_median'] = np.median(signal)
        features[f'{sensor}_rms'] = np.sqrt(np.mean(signal ** 2))

    feature_rows.append(features)


# Create final feature dataset
feature_df = pd.DataFrame(feature_rows)

print("Feature dataset shape:", feature_df.shape)

print("\nActivity distribution:")
print(feature_df['Activity'].value_counts())

print("\nMissing values:")
print(feature_df.isnull().sum().sum())

display(feature_df.head())

# EDA: FEATURE COMPARISON

# Get all statistical feature columns
feature_cols = [
    col for col in feature_df.columns
    if col not in ['window_id', 'segment_id', 'Activity']
]

# Compare mean feature values by activity
feature_means = feature_df.groupby('Activity')[feature_cols].mean().T

display(feature_means)

# Absolute difference between Activity 0 and Activity 1
feature_difference = (
    feature_means[1] - feature_means[0]
).abs().sort_values(ascending=False)

print("Top 20 features with largest mean difference:")
display(feature_difference.head(20))

# FEATURE SELECTION - MUTUAL INFORMATION

from sklearn.feature_selection import mutual_info_classif

X = feature_df[feature_cols]
y = feature_df['Activity']

mi_scores = mutual_info_classif(
    X,
    y,
    random_state=42
)

mi_df = pd.DataFrame({
    'Feature': feature_cols,
    'MI_Score': mi_scores
}).sort_values(
    'MI_Score',
    ascending=False
).reset_index(drop=True)

print("Top 20 features by Mutual Information:")

display(mi_df.head(20))

# STEP: TRAIN / TEST SPLIT BY SEGMENT

from sklearn.model_selection import train_test_split

# Get unique segment IDs and their corresponding activity
segment_labels = (
    feature_df[['segment_id', 'Activity']]
    .drop_duplicates()
)

# Split segments, not individual windows
train_segments, test_segments = train_test_split(
    segment_labels['segment_id'],
    test_size=0.20,
    random_state=42,
    stratify=segment_labels['Activity']
)

# Create train and test datasets
train_df = feature_df[
    feature_df['segment_id'].isin(train_segments)
].copy()

test_df = feature_df[
    feature_df['segment_id'].isin(test_segments)
].copy()

# Reset indexes
train_df.reset_index(drop=True, inplace=True)
test_df.reset_index(drop=True, inplace=True)

# CHECK THE SPLIT

print("Training segments:", len(train_segments))
print("Testing segments:", len(test_segments))

print("\nTraining shape:", train_df.shape)
print("Testing shape:", test_df.shape)

print("\nTraining activity distribution:")
print(train_df['Activity'].value_counts())

print("\nTesting activity distribution:")
print(test_df['Activity'].value_counts())

print("\nTraining activity percentage:")
print(train_df['Activity'].value_counts(normalize=True) * 100)

print("\nTesting activity percentage:")
print(test_df['Activity'].value_counts(normalize=True) * 100)

# CHECK FOR SEGMENT LEAKAGE

overlap = set(train_df['segment_id']) & set(test_df['segment_id'])

print("Segments appearing in BOTH train and test:", len(overlap))

# STEP: SEPARATE FEATURES AND TARGET

# Columns that should NOT be used as model features
drop_cols = ['window_id', 'segment_id', 'Activity']

# Training data
X_train = train_df.drop(columns=drop_cols)
y_train = train_df['Activity']

# Testing data
X_test = test_df.drop(columns=drop_cols)
y_test = test_df['Activity']

# Check shapes
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_test :", X_test.shape)
print("y_test :", y_test.shape)

print("\nFeature columns:")
print(X_train.columns.tolist())

print("\nTarget distribution:")
print("Train:")
print(y_train.value_counts())

print("\nTest:")
print(y_test.value_counts())

# STEP: FEATURE SELECTION USING MUTUAL INFORMATION


from sklearn.feature_selection import SelectKBest, mutual_info_classif

# Select top 20 features
selector = SelectKBest(
    score_func=mutual_info_classif,
    k=20
)

# IMPORTANT:
# Fit feature selection ONLY on training data
X_train_selected = selector.fit_transform(X_train, y_train)

# Apply the SAME selector to test data
X_test_selected = selector.transform(X_test)

# Get selected feature names
selected_features = X_train.columns[selector.get_support()]

print("Selected features:")
for i, feature in enumerate(selected_features, 1):
    print(f"{i}. {feature}")

print("\nOriginal number of features:", X_train.shape[1])
print("Selected number of features:", X_train_selected.shape[1])

print("\nX_train_selected shape:", X_train_selected.shape)
print("X_test_selected shape :", X_test_selected.shape)

# MUTUAL INFORMATION SCORES


mi_scores = pd.DataFrame({
    'Feature': X_train.columns,
    'MI_Score': selector.scores_
})

mi_scores = mi_scores.sort_values(
    by='MI_Score',
    ascending=False
).reset_index(drop=True)

print(mi_scores.head(20))

# STEP: FEATURE SCALING


from sklearn.preprocessing import StandardScaler

# Create scaler
scaler = StandardScaler()

# Fit ONLY on training data
X_train_scaled = scaler.fit_transform(X_train_selected)

# Use the same scaler on test data
X_test_scaled = scaler.transform(X_test_selected)

# Check shapes
print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape :", X_test_scaled.shape)

# Check mean and standard deviation of training data
print("\nTraining feature means:")
print(np.mean(X_train_scaled, axis=0))

print("\nTraining feature standard deviations:")
print(np.std(X_train_scaled, axis=0))

"""***Using XGBoost for class imbalance proble***"""

# XGBOOST WITH ACTIVITY-0 CLASS WEIGHTING

from xgboost import XGBClassifier
import numpy as np

# Calculate class weight
class_0 = (y_train == 0).sum()
class_1 = (y_train == 1).sum()

minority_weight = class_1 / class_0

print("Activity 0:", class_0)
print("Activity 1:", class_1)
print("Activity 0 weight:", minority_weight)

# Assign weight to each training sample
sample_weights = np.where(
    y_train == 0,
    minority_weight,
    1.0
)

# Create XGBoost model
xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    eval_metric='logloss',
    random_state=42,
    n_jobs=-1
)

# Train using sample weights
xgb_model.fit(
    X_train_scaled,
    y_train,
    sample_weight=sample_weights
)

print("\nXGBoost model trained successfully!")

# EVALUATE XGBOOST MODEL


from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    balanced_accuracy_score,
    roc_auc_score
)

# Make predictions on TEST data
y_pred = xgb_model.predict(X_test_scaled)

# Probability of Activity 1
y_prob = xgb_model.predict_proba(X_test_scaled)[:, 1]

# Confusion Matrix


cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

# Classification Report

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    digits=4
))

# Balanced Accuracy

balanced_acc = balanced_accuracy_score(y_test, y_pred)

print("Balanced Accuracy:", round(balanced_acc, 4))

# ROC-AUC

roc_auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", round(roc_auc, 4))

# Accuracy: 99.27%
# Balanced Accuracy: 83.11%
# ROC-AUC: 0.9912

# Correctly detected 4/6 Activity 0 windows
# Missed 2/6 Activity 0 windows
# Incorrectly classified 3 Activity 1 windows as Activity 0
# Correctly classified 676/679 Activity 1 windows

# ROC-AUC of 0.9912 is very high, while Activity-0 F1 is only 0.6154.

# That suggests the model's probability ranking is strong,
# but the default classification threshold of 0.5 may not be the best threshold for detecting Activity 0.

"""**Fold Stratified Group Cross-Validation for stability check across different segments**"""

# STEP: 5-FOLD STRATIFIED GROUP CROSS-VALIDATION WITH XGBOOST

from sklearn.model_selection import StratifiedGroupKFold
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    balanced_accuracy_score,
    roc_auc_score
)

from xgboost import XGBClassifier


# 1. Prepare data

# Use the original 56-feature training data.
# Test data is NOT used in cross-validation.

X_cv = train_df.drop(
    columns=['window_id', 'segment_id', 'Activity']
)

y_cv = train_df['Activity']

groups = train_df['segment_id']


# 2. Create Stratified Group K-Fold

cv = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


# 3. Store results

results = []

all_y_true = []
all_y_pred = []
all_y_prob = []


# 4. Cross-validation

for fold, (train_idx, val_idx) in enumerate(
    cv.split(X_cv, y_cv, groups=groups),
    start=1
):

    print("=" * 60)
    print(f"FOLD {fold}")
    print("=" * 60)

    # Split by segment
    X_train_fold = X_cv.iloc[train_idx].copy()
    X_val_fold = X_cv.iloc[val_idx].copy()

    y_train_fold = y_cv.iloc[train_idx].copy()
    y_val_fold = y_cv.iloc[val_idx].copy()

    groups_train = groups.iloc[train_idx]
    groups_val = groups.iloc[val_idx]

    print("Training samples:", len(X_train_fold))
    print("Validation samples:", len(X_val_fold))

    print(
        "Training Activity 0:",
        (y_train_fold == 0).sum()
    )

    print(
        "Validation Activity 0:",
        (y_val_fold == 0).sum()
    )

    print(
        "Train/Validation group overlap:",
        len(set(groups_train) & set(groups_val))
    )


    # 5. Feature selection

    selector_cv = SelectKBest(
        score_func=mutual_info_classif,
        k=20
    )

    X_train_selected = selector_cv.fit_transform(
        X_train_fold,
        y_train_fold
    )

    X_val_selected = selector_cv.transform(
        X_val_fold
    )


    # 6. Scaling

    scaler_cv = StandardScaler()

    X_train_scaled_cv = scaler_cv.fit_transform(
        X_train_selected
    )

    X_val_scaled_cv = scaler_cv.transform(
        X_val_selected
    )


    # 7. Calculate Activity-0 weight

    class_0 = (y_train_fold == 0).sum()
    class_1 = (y_train_fold == 1).sum()

    minority_weight = class_1 / class_0


    # Give Activity 0 more importance
    sample_weights = np.where(
        y_train_fold == 0,
        minority_weight,
        1.0
    )


    # 8. Train XGBoost

    xgb_cv = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective='binary:logistic',
        eval_metric='logloss',
        random_state=42,
        n_jobs=-1
    )

    xgb_cv.fit(
        X_train_scaled_cv,
        y_train_fold,
        sample_weight=sample_weights
    )


    # 9. Predictions

    y_pred_fold = xgb_cv.predict(
        X_val_scaled_cv
    )

    y_prob_fold = xgb_cv.predict_proba(
        X_val_scaled_cv
    )[:, 1]


    # 10. Metrics

    precision_0 = precision_score(
        y_val_fold,
        y_pred_fold,
        pos_label=0,
        zero_division=0
    )

    recall_0 = recall_score(
        y_val_fold,
        y_pred_fold,
        pos_label=0,
        zero_division=0
    )

    f1_0 = f1_score(
        y_val_fold,
        y_pred_fold,
        pos_label=0,
        zero_division=0
    )

    balanced_acc = balanced_accuracy_score(
        y_val_fold,
        y_pred_fold
    )

    roc_auc = roc_auc_score(
        y_val_fold,
        y_prob_fold
    )


    # 11. Save fold results

    results.append({
        'Fold': fold,
        'Train Samples': len(train_idx),
        'Validation Samples': len(val_idx),
        'Train Activity 0': class_0,
        'Validation Activity 0': (y_val_fold == 0).sum(),
        'Precision_0': precision_0,
        'Recall_0': recall_0,
        'F1_0': f1_0,
        'Balanced Accuracy': balanced_acc,
        'ROC-AUC': roc_auc
    })


    # Store predictions for overall analysis
    all_y_true.extend(y_val_fold)
    all_y_pred.extend(y_pred_fold)
    all_y_prob.extend(y_prob_fold)


# 12. Results table

results_df = pd.DataFrame(results)

print("\n\n")
print("=" * 80)
print("CROSS-VALIDATION RESULTS")
print("=" * 80)

print(
    results_df.to_string(index=False)
)


# 13. Average CV performance

print("\n")
print("=" * 80)
print("AVERAGE CROSS-VALIDATION PERFORMANCE")
print("=" * 80)

print(
    "\nActivity 0 Precision:",
    round(results_df['Precision_0'].mean(), 4)
)

print(
    "Activity 0 Recall:",
    round(results_df['Recall_0'].mean(), 4)
)

print(
    "Activity 0 F1:",
    round(results_df['F1_0'].mean(), 4)
)

print(
    "Balanced Accuracy:",
    round(results_df['Balanced Accuracy'].mean(), 4)
)

print(
    "ROC-AUC:",
    round(results_df['ROC-AUC'].mean(), 4)
)



# 14. Overall out-of-fold confusion matrix


all_y_true = np.array(all_y_true)
all_y_pred = np.array(all_y_pred)

print("\n")
print("=" * 80)
print("OVERALL OUT-OF-FOLD CONFUSION MATRIX")
print("=" * 80)

print(
    confusion_matrix(
        all_y_true,
        all_y_pred
    )
)

# Fold 5 has:

# Training Activity 0:     36
# Validation Activity 0:    0

# That means all Activity-0 segments ended up in the training set for Fold 5. Therefore:

# Activity-0 recall cannot be meaningfully evaluated in Fold 5.
# ROC-AUC is NaN.
# Its balanced accuracy of 0.998 is misleading.
# Averaging this fold with the others is not appropriate.

# your dataset has only 10 Activity-0 segments, and their window counts are highly uneven

# LEAVE-ONE-ACTIVITY-0-SEGMENT-OUT CROSS-VALIDATION

from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    balanced_accuracy_score,
    roc_auc_score
)

from xgboost import XGBClassifier


# 1. Prepare the training dataset

X_all = train_df.drop(
    columns=['window_id', 'segment_id', 'Activity']
)

y_all = train_df['Activity']

groups_all = train_df['segment_id']


# Get ONLY Activity-0 segments
activity0_segments = sorted(
    train_df.loc[
        train_df['Activity'] == 0,
        'segment_id'
    ].unique()
)

print("Number of Activity-0 segments:",
      len(activity0_segments))

print("\nActivity-0 segments:")
print(activity0_segments)


# 2. Store results

results = []

all_y_true = []
all_y_pred = []
all_y_prob = []



# 3. Leave one Activity-0 segment out

for fold, test_segment in enumerate(
    activity0_segments,
    start=1
):

    print("\n" + "=" * 70)
    print(f"FOLD {fold}")
    print(f"Held-out Activity-0 segment: {test_segment}")
    print("=" * 70)


    # Validation = ONE complete Activity-0 segment

    val_mask = (
        groups_all == test_segment
    )

    train_mask = ~val_mask


    X_train_fold = X_all.loc[train_mask].copy()
    y_train_fold = y_all.loc[train_mask].copy()

    X_val_fold = X_all.loc[val_mask].copy()
    y_val_fold = y_all.loc[val_mask].copy()


    print("Training samples:",
          len(X_train_fold))

    print("Validation samples:",
          len(X_val_fold))

    print("Training Activity 0:",
          (y_train_fold == 0).sum())

    print("Training Activity 1:",
          (y_train_fold == 1).sum())

    print("Validation Activity 0:",
          (y_val_fold == 0).sum())



    # 4. Feature selection

    selector = SelectKBest(
        score_func=mutual_info_classif,
        k=20
    )

    X_train_selected = selector.fit_transform(
        X_train_fold,
        y_train_fold
    )

    X_val_selected = selector.transform(
        X_val_fold
    )


    # 5. Scaling

    scaler = StandardScaler()

    X_train_scaled = scaler.fit_transform(
        X_train_selected
    )

    X_val_scaled = scaler.transform(
        X_val_selected
    )


    # 6. Activity-0 sample weighting

    class_0 = (y_train_fold == 0).sum()
    class_1 = (y_train_fold == 1).sum()

    activity0_weight = class_1 / class_0

    sample_weights = np.where(
        y_train_fold == 0,
        activity0_weight,
        1.0
    )


    # 7. Train XGBoost

    model = XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective='binary:logistic',
        eval_metric='logloss',
        random_state=42,
        n_jobs=-1
    )

    model.fit(
        X_train_scaled,
        y_train_fold,
        sample_weight=sample_weights
    )


    # 8. Predictions

    y_pred = model.predict(
        X_val_scaled
    )

    y_prob = model.predict_proba(
        X_val_scaled
    )[:, 1]


    # 9. Activity-0 metrics

    precision_0 = precision_score(
        y_val_fold,
        y_pred,
        pos_label=0,
        zero_division=0
    )

    recall_0 = recall_score(
        y_val_fold,
        y_pred,
        pos_label=0,
        zero_division=0
    )

    f1_0 = f1_score(
        y_val_fold,
        y_pred,
        pos_label=0,
        zero_division=0
    )


    # 10. Confusion matrix

    cm = confusion_matrix(
        y_val_fold,
        y_pred,
        labels=[0, 1]
    )



    # 11. Store results

    results.append({
        'Fold': fold,
        'Held_Out_Segment': test_segment,
        'Validation_Activity0_Windows': len(y_val_fold),
        'Activity0_Precision': precision_0,
        'Activity0_Recall': recall_0,
        'Activity0_F1': f1_0,
        'Predicted_Activity0': (y_pred == 0).sum(),
        'Correct_Activity0': (
            (y_val_fold == 0) &
            (y_pred == 0)
        ).sum()
    })


    print("\nConfusion Matrix:")
    print(cm)

    print("\nActivity-0 Precision:",
          round(precision_0, 4))

    print("Activity-0 Recall:",
          round(recall_0, 4))

    print("Activity-0 F1:",
          round(f1_0, 4))


    # Store predictions
    all_y_true.extend(y_val_fold)
    all_y_pred.extend(y_pred)
    all_y_prob.extend(y_prob)


# 12. Results summary

results_df = pd.DataFrame(results)

print("\n\n")
print("=" * 80)
print("LEAVE-ONE-ACTIVITY-0-SEGMENT-OUT RESULTS")
print("=" * 80)

print(
    results_df.to_string(index=False)
)


# 13. Overall Activity-0 performance

print("\n")
print("=" * 80)
print("OVERALL ACTIVITY-0 PERFORMANCE")
print("=" * 80)

print(
    "\nActivity-0 Precision:",
    round(
        precision_score(
            all_y_true,
            all_y_pred,
            pos_label=0,
            zero_division=0
        ),
        4
    )
)

print(
    "Activity-0 Recall:",
    round(
        recall_score(
            all_y_true,
            all_y_pred,
            pos_label=0,
            zero_division=0
        ),
        4
    )
)

print(
    "Activity-0 F1:",
    round(
        f1_score(
            all_y_true,
            all_y_pred,
            pos_label=0,
            zero_division=0
        ),
        4
    )
)

print("\nOverall Confusion Matrix:")
print(
    confusion_matrix(
        all_y_true,
        all_y_pred,
        labels=[0, 1]
    )
)

# ============================================
# STEP: ACTIVITY-0 SEGMENT DIAGNOSTICS
# ============================================

activity0_segments = (
    df[df['Activity'] == 0]
    .groupby('segment_id')
    .agg(
        samples=('Activity', 'size'),
        start_time=('time_seconds', 'min'),
        end_time=('time_seconds', 'max')
    )
    .reset_index()
)

activity0_segments['duration_sec'] = (
    activity0_segments['end_time']
    - activity0_segments['start_time']
)

# Number of 2-second windows generated from each segment
window_counts = (
    windows_df[windows_df['Activity'] == 0]
    .groupby('segment_id')
    .size()
    .reset_index(name='windows')
)

activity0_segments = activity0_segments.merge(
    window_counts,
    on='segment_id',
    how='left'
)

activity0_segments['windows'] = (
    activity0_segments['windows']
    .fillna(0)
    .astype(int)
)

activity0_segments = activity0_segments.sort_values(
    'start_time'
).reset_index(drop=True)

print(activity0_segments)

print("\nTotal Activity-0 segments:",
      len(activity0_segments))

print("\nTotal Activity-0 samples:",
      activity0_segments['samples'].sum())

print("\nTotal Activity-0 windows:",
      activity0_segments['windows'].sum())

print("\nActivity-0 segment duration statistics:")
print(
    activity0_segments[
        ['samples', 'duration_sec', 'windows']
    ].describe()
)

# The biggest issue is not simply class imbalance. It is the very small number of independent Activity-0 episodes.

# You have 571 Activity-0 samples, but they come from only 10 separate episodes. After 2-second windowing, those become only 42 windows.

# And because of the 50% overlap, those 42 windows are not 42 independent observations. Adjacent windows share 10 of their 20 samples.

# STEP: COMPARE ACTIVITY-0 SEGMENTS


sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ'
]

segment_sensor_stats = (
    df[df['Activity'] == 0]
    .groupby('segment_id')[sensor_cols]
    .agg(['mean', 'std'])
)

print(segment_sensor_stats)

# Mean of each sensor for every Activity-0 segment

segment_means = (
    df[df['Activity'] == 0]
    .groupby('segment_id')[sensor_cols]
    .mean()
    .round(3)
)

print("Activity-0 segment means:")
print(segment_means)

# Standard deviation of each sensor for every Activity-0 segment

segment_stds = (
    df[df['Activity'] == 0]
    .groupby('segment_id')[sensor_cols]
    .std()
    .round(3)
)

print("\nActivity-0 segment standard deviations:")
print(segment_stds)

# "low acceleration = standing"
#
# SEGMENT-LEVEL CLASS SEPARATION

segment_features = []

for segment_id, segment in df.groupby('segment_id'):

    row = {
        'segment_id': segment_id,
        'Activity': segment['Activity'].iloc[0]
    }

    for sensor in feature_sensor_cols:

        signal = segment[sensor].values

        row[f'{sensor}_mean'] = np.mean(signal)
        row[f'{sensor}_std'] = np.std(signal)
        row[f'{sensor}_range'] = np.ptp(signal)
        row[f'{sensor}_rms'] = np.sqrt(np.mean(signal ** 2))

    segment_features.append(row)

segment_feature_df = pd.DataFrame(segment_features)

print("Shape:", segment_feature_df.shape)

print("\nActivity distribution:")
print(segment_feature_df['Activity'].value_counts())

print("\nSegment-level feature statistics:")
print(
    segment_feature_df
    .groupby('Activity')
    .mean(numeric_only=True)
    .T
)

# Activity 0 → relatively stable acceleration

# Activity 1 → substantially greater acceleration variation

# ACCELERATION / GYRO MAGNITUDE SEPARATION

magnitude_features = [
    'acc_mag_mean',
    'acc_mag_std',
    'acc_mag_range',
    'acc_mag_rms',
    'gyro_mag_mean',
    'gyro_mag_std',
    'gyro_mag_range',
    'gyro_mag_rms'
]

magnitude_summary = (
    segment_feature_df
    .groupby('Activity')[magnitude_features]
    .mean()
    .T
)

print("Mean magnitude features by Activity:")
print(magnitude_summary.round(4))

# DIFFERENCE BETWEEN ACTIVITY 0 AND 1

magnitude_difference = pd.DataFrame({
    'Activity_0': segment_feature_df[
        segment_feature_df['Activity'] == 0
    ][magnitude_features].mean(),

    'Activity_1': segment_feature_df[
        segment_feature_df['Activity'] == 1
    ][magnitude_features].mean()
})

magnitude_difference['abs_difference'] = (
    magnitude_difference['Activity_1']
    - magnitude_difference['Activity_0']
).abs()

print("\nMagnitude feature differences:")
print(
    magnitude_difference
    .sort_values('abs_difference', ascending=False)
    .round(4)
)

# The distinction is primarily in the amount of movement/variation, not the average acceleration level.

# STEP: DYNAMIC MOVEMENT FEATURES


# Change in acceleration magnitude
df['acc_mag_diff'] = df['acc_mag'].diff()

# Change in gyroscope magnitude
df['gyro_mag_diff'] = df['gyro_mag'].diff()

print(df[
    ['acc_mag', 'acc_mag_diff',
     'gyro_mag', 'gyro_mag_diff']
].head(10))

# COMPARE DYNAMIC FEATURES BY ACTIVITY

dynamic_stats = (
    df.groupby('Activity')[
        ['acc_mag_diff', 'gyro_mag_diff']
    ]
    .agg(['mean', 'std', 'min', 'max'])
)

print(dynamic_stats.round(4))

# ABSOLUTE SAMPLE-TO-SAMPLE CHANGE

df['acc_mag_abs_diff'] = df['acc_mag_diff'].abs()
df['gyro_mag_abs_diff'] = df['gyro_mag_diff'].abs()

dynamic_comparison = (
    df.groupby('Activity')[
        ['acc_mag_abs_diff', 'gyro_mag_abs_diff']
    ]
    .agg(['mean', 'std', 'median', 'max'])
)

print(dynamic_comparison.round(4))

#
# STEP: REBUILD WINDOWS WITH DYNAMIC FEATURES

feature_sensor_cols = [
    'accX', 'accY', 'accZ',
    'gyroX', 'gyroY', 'gyroZ',
    'acc_mag', 'gyro_mag',
    'acc_mag_abs_diff',
    'gyro_mag_abs_diff'
]

WINDOW_SIZE = 20
STEP_SIZE = 10

windows = []
window_id = 0

for segment_id, segment in df.groupby('segment_id'):

    segment = segment.reset_index(drop=True)

    for start in range(
        0,
        len(segment) - WINDOW_SIZE + 1,
        STEP_SIZE
    ):

        end = start + WINDOW_SIZE
        window = segment.iloc[start:end]

        windows.append({
            'window_id': window_id,
            'segment_id': segment_id,
            'Activity': window['Activity'].iloc[0],
            'start_time': window['time_seconds'].iloc[0],
            'end_time': window['time_seconds'].iloc[-1],
            'samples': len(window),
            'data': window[feature_sensor_cols].values
        })

        window_id += 1

windows_df = pd.DataFrame(windows)

print("Total windows:", len(windows_df))
print("\nActivity distribution:")
print(windows_df['Activity'].value_counts())

# STEP: EXTRACT WINDOW FEATURES

feature_rows = []

for _, row in windows_df.iterrows():

    data = row['data']

    features = {
        'window_id': row['window_id'],
        'segment_id': row['segment_id'],
        'Activity': row['Activity']
    }

    # ----------------------------------------
    # Existing sensor features
    # ----------------------------------------

    for i, sensor in enumerate(feature_sensor_cols):

        signal = data[:, i]

        features[f'{sensor}_mean'] = np.mean(signal)
        features[f'{sensor}_std'] = np.std(signal)
        features[f'{sensor}_min'] = np.min(signal)
        features[f'{sensor}_max'] = np.max(signal)
        features[f'{sensor}_range'] = np.ptp(signal)
        features[f'{sensor}_median'] = np.median(signal)
        features[f'{sensor}_rms'] = np.sqrt(
            np.mean(signal ** 2)
        )

    feature_rows.append(features)

feature_df = pd.DataFrame(feature_rows)

print("Feature dataset shape:", feature_df.shape)

print("\nActivity distribution:")
print(feature_df['Activity'].value_counts())

print("\nNumber of features:",
      len(feature_df.columns) - 3)

# STEP: CHECK FEATURE QUALITY

# Separate feature columns from metadata
feature_cols = [
    col for col in feature_df.columns
    if col not in ['window_id', 'segment_id', 'Activity']
]

X = feature_df[feature_cols]

# Check missing values
nan_counts = X.isna().sum()

print("Total NaN values:", nan_counts.sum())

print("\nFeatures containing NaN:")
print(nan_counts[nan_counts > 0])

# Check infinite values
inf_counts = np.isinf(X).sum()

print("\nTotal infinite values:", inf_counts.sum())

print("\nFeatures containing infinity:")
print(inf_counts[inf_counts > 0])

print("\nNumber of feature columns:", len(feature_cols))
print("Expected:", 70)

# Check which windows contain NaN values
nan_windows = feature_df[
    feature_df[feature_cols].isna().any(axis=1)
]

print("Number of affected windows:", len(nan_windows))

print("\nAffected windows:")
print(nan_windows[['window_id', 'segment_id', 'Activity']])

print("\nActivity distribution of affected windows:")
print(nan_windows['Activity'].value_counts())

feature_df_clean = feature_df.dropna(
    subset=feature_cols
).reset_index(drop=True)

print("Original shape:", feature_df.shape)
print("Clean shape:", feature_df_clean.shape)

print("\nActivity distribution:")
print(feature_df_clean['Activity'].value_counts())

X_clean = feature_df_clean[feature_cols]

print("Total NaN values:", X_clean.isna().sum().sum())
print("Total infinite values:", np.isinf(X_clean).sum().sum())

from sklearn.model_selection import train_test_split

# Get unique segments and their activity labels
segment_labels = (
    feature_df_clean[['segment_id', 'Activity']]
    .drop_duplicates()
)

print("Total segments:", len(segment_labels))
print("\nSegment distribution:")
print(segment_labels['Activity'].value_counts())

# Split SEGMENTS, not individual windows
train_segments, test_segments = train_test_split(
    segment_labels['segment_id'],
    test_size=0.20,
    random_state=42,
    stratify=segment_labels['Activity']
)

# Create train and test datasets
train_df = feature_df_clean[
    feature_df_clean['segment_id'].isin(train_segments)
].copy()

test_df = feature_df_clean[
    feature_df_clean['segment_id'].isin(test_segments)
].copy()

train_df.reset_index(drop=True, inplace=True)
test_df.reset_index(drop=True, inplace=True)

print("\nTraining shape:", train_df.shape)
print("Testing shape:", test_df.shape)

print("\nTraining segments:", train_df['segment_id'].nunique())
print("Testing segments:", test_df['segment_id'].nunique())

print("\nTraining Activity distribution:")
print(train_df['Activity'].value_counts())

print("\nTesting Activity distribution:")
print(test_df['Activity'].value_counts())

# Check whether any segment appears in both train and test
overlap = set(train_segments) & set(test_segments)

print("\nSegment overlap:", len(overlap))

if len(overlap) == 0:
    print("No segment overlap — split is leakage-safe.")
else:
    print(" Leakage detected!")
    print("Overlapping segments:", overlap)

# Columns that are NOT model features
drop_cols = ['window_id', 'segment_id', 'Activity']

# Training data
X_train = train_df.drop(columns=drop_cols)
y_train = train_df['Activity']

# Testing data
X_test = test_df.drop(columns=drop_cols)
y_test = test_df['Activity']

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

print("\nTraining class distribution:")
print(y_train.value_counts())

print("\nTesting class distribution:")
print(y_test.value_counts())

from sklearn.feature_selection import mutual_info_classif
import pandas as pd
import numpy as np

# Calculate Mutual Information using TRAINING DATA ONLY
mi_scores = mutual_info_classif(
    X_train,
    y_train,
    random_state=42
)

# Create ranking table
mi_df = pd.DataFrame({
    'Feature': X_train.columns,
    'MI_Score': mi_scores
})

# Sort from highest to lowest
mi_df = mi_df.sort_values(
    by='MI_Score',
    ascending=False
).reset_index(drop=True)

print("Top 20 features based on Mutual Information:\n")
print(mi_df.head(20).to_string(index=False))

# Select top 20 features
k = 20

selected_features = mi_df.head(k)['Feature'].tolist()

print("Selected features:")
for i, feature in enumerate(selected_features, start=1):
    print(f"{i}. {feature}")

print("\nNumber of selected features:", len(selected_features))

X_train_selected = X_train[selected_features].copy()
X_test_selected = X_test[selected_features].copy()

print("X_train_selected shape:", X_train_selected.shape)
print("X_test_selected shape:", X_test_selected.shape)

from sklearn.preprocessing import StandardScaler

# Create scaler
scaler = StandardScaler()

# Fit ONLY on training data
X_train_scaled = scaler.fit_transform(X_train_selected)

# Apply the same transformation to test data
X_test_scaled = scaler.transform(X_test_selected)

print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

print("\nTraining feature means:")
print(X_train_scaled.mean(axis=0).round(4))

print("\nTraining feature standard deviations:")
print(X_train_scaled.std(axis=0).round(4))

"""**Logistic Regression**"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    balanced_accuracy_score,
    roc_auc_score,
    f1_score
)

# Create baseline Logistic Regression model
logreg = LogisticRegression(
    class_weight='balanced',
    max_iter=1000,
    random_state=42
)

# Train
logreg.fit(X_train_scaled, y_train)

# Predictions
y_pred = logreg.predict(X_test_scaled)
y_prob = logreg.predict_proba(X_test_scaled)[:, 1]

# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))

# Additional metrics
print("Balanced Accuracy:",
      round(balanced_accuracy_score(y_test, y_pred), 4))

print("Macro F1:",
      round(f1_score(y_test, y_pred, average='macro'), 4))

print("ROC-AUC:",
      round(roc_auc_score(y_test, y_prob), 4))

# All 6 Activity-0 test windows were detected → recall = 100%
# But 17 Activity-1 windows were incorrectly classified as Activity 0
# Therefore Activity-0 precision is only 26.09%
# Activity-0 F1 = 0.4138
# The model is being very aggressive about detecting Activity 0.

"""**Random Forest**"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    balanced_accuracy_score,
    roc_auc_score,
    f1_score
)

# Random Forest baseline
rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

# Train on selected features
# Scaling is not required for Random Forest,
# but using the already prepared data is okay.
rf_model.fit(X_train_selected, y_train)

# Predictions
y_pred_rf = rf_model.predict(X_test_selected)
y_prob_rf = rf_model.predict_proba(X_test_selected)[:, 1]

# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf, digits=4))

# Additional metrics
print("Balanced Accuracy:",
      round(balanced_accuracy_score(y_test, y_pred_rf), 4))

print("Macro F1:",
      round(f1_score(y_test, y_pred_rf, average='macro'), 4))

print("ROC-AUC:",
      round(roc_auc_score(y_test, y_prob_rf), 4))

# Detected only 1 of 6 Activity-0 windows
# Missed 5 Activity-0 windows
# Made zero false Activity-0 predictions
# Correctly classified all 679 Activity-1 windows

"""**XGBoost**"""

from xgboost import XGBClassifier
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    balanced_accuracy_score,
    f1_score,
    roc_auc_score
)

# 1. Calculate class weight for minority class (0)

class_0 = (y_train == 0).sum()
class_1 = (y_train == 1).sum()

minority_weight = class_1 / class_0

print("Activity 0 training samples:", class_0)
print("Activity 1 training samples:", class_1)
print("Activity 0 weight:", round(minority_weight, 4))

# Give higher weight to Activity 0
sample_weights = np.where(
    y_train == 0,
    minority_weight,
    1.0
)

# 2. Create XGBoost model

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,

    objective='binary:logistic',
    eval_metric='logloss',

    random_state=42,
    n_jobs=-1
)

# 3. Train


xgb_model.fit(
    X_train_selected,
    y_train,
    sample_weight=sample_weights
)


# 4. Predictions

y_pred_xgb = xgb_model.predict(X_test_selected)

y_prob_xgb = xgb_model.predict_proba(
    X_test_selected
)[:, 1]

# 5. Evaluation


print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_xgb,
        digits=4
    )
)

print(
    "Balanced Accuracy:",
    round(
        balanced_accuracy_score(
            y_test,
            y_pred_xgb
        ),
        4
    )
)

print(
    "Macro F1:",
    round(
        f1_score(
            y_test,
            y_pred_xgb,
            average='macro'
        ),
        4
    )
)

print(
    "ROC-AUC:",
    round(
        roc_auc_score(
            y_test,
            y_prob_xgb
        ),
        4
    )
)

# This is the best of the three models so far on the current holdout.

# it correctly detects 4 of the 6 Activity-0 windows, while producing only 1 false Activity-0 prediction.

# That's a much better balance than the other two models.

"""**Using the SMOTE**"""

from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    balanced_accuracy_score,
    f1_score,
    roc_auc_score
)


# 1. Apply SMOTE ONLY to training data


print("Before SMOTE:")
print(y_train.value_counts())

smote = SMOTE(
    random_state=42,
    k_neighbors=5
)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train_selected,
    y_train
)

print("\nAfter SMOTE:")
print(y_train_smote.value_counts())

print("\nOriginal training shape:", X_train_selected.shape)
print("SMOTE training shape:", X_train_smote.shape)


# 2. Create XGBoost model


xgb_smote = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,

    objective='binary:logistic',
    eval_metric='logloss',

    random_state=42,
    n_jobs=-1
)


# 3. Train on SMOTE-balanced training data


xgb_smote.fit(
    X_train_smote,
    y_train_smote
)

# 4. Predict on ORIGINAL untouched test data


y_pred_smote = xgb_smote.predict(X_test_selected)

y_prob_smote = xgb_smote.predict_proba(
    X_test_selected
)[:, 1]


# 5. Evaluation

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_smote))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_smote,
        digits=4
    )
)

print(
    "Balanced Accuracy:",
    round(
        balanced_accuracy_score(
            y_test,
            y_pred_smote
        ),
        4
    )
)

print(
    "Macro F1:",
    round(
        f1_score(
            y_test,
            y_pred_smote,
            average='macro'
        ),
        4
    )
)

print(
    "ROC-AUC:",
    round(
        roc_auc_score(
            y_test,
            y_prob_smote
        ),
        4
    )
)

# SMOTE detected 5/6 Activity-0 windows, but incorrectly classified 12 Activity-1 windows as Activity 0.

# Can our model recognize a completely unseen standing episode, rather than merely recognize windows that resemble
# the few standing windows it saw during training?

"""**Segment validation before testing on test data**"""

# UNSEEN ACTIVITY-0 SEGMENT VALIDATION
# XGBoost: Class Weight vs SMOTE

from sklearn.feature_selection import mutual_info_classif
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier

from sklearn.metrics import (
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

## Settings


K_FEATURES = 20

# All Activity-0 segments available in the complete dataset
activity0_segments = sorted(
    feature_df_clean.loc[
        feature_df_clean['Activity'] == 0,
        'segment_id'
    ].unique()
)

print("Activity-0 segments:", activity0_segments)
print("Number of Activity-0 segments:", len(activity0_segments))



# Store results


results = []

all_y_true = []
all_pred_weight = []
all_pred_smote = []



# Leave one Activity-0 segment out


for i, val_segment in enumerate(activity0_segments, start=1):

    print(f"\n{'='*60}")
    print(f"Fold {i}: Activity-0 segment {val_segment}")
    print(f"{'='*60}")


    # Validation = ONE complete Activity-0 segment
    # Training = every other segment


    train_fold = feature_df_clean[
        feature_df_clean['segment_id'] != val_segment
    ].copy()

    val_fold = feature_df_clean[
        feature_df_clean['segment_id'] == val_segment
    ].copy()


    # Remove metadata


    X_tr = train_fold.drop(
        columns=['window_id', 'segment_id', 'Activity']
    )

    y_tr = train_fold['Activity']

    X_val = val_fold.drop(
        columns=['window_id', 'segment_id', 'Activity']
    )

    y_val = val_fold['Activity']



    mi_scores_fold = mutual_info_classif(
        X_tr,
        y_tr,
        random_state=42
    )

    mi_fold = pd.DataFrame({
        'Feature': X_tr.columns,
        'MI': mi_scores_fold
    }).sort_values(
        'MI',
        ascending=False
    )

    selected_fold_features = (
        mi_fold.head(K_FEATURES)['Feature'].tolist()
    )

    X_tr_selected = X_tr[selected_fold_features]
    X_val_selected = X_val[selected_fold_features]


    # MODEL 1: XGBoost + class weighting


    class_0 = (y_tr == 0).sum()
    class_1 = (y_tr == 1).sum()

    minority_weight = class_1 / class_0

    sample_weights = np.where(
        y_tr == 0,
        minority_weight,
        1.0
    )

    xgb_weight = XGBClassifier(
        n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective='binary:logistic',
        eval_metric='logloss',
        random_state=42,
        n_jobs=-1
    )

    xgb_weight.fit(
        X_tr_selected,
        y_tr,
        sample_weight=sample_weights
    )

    pred_weight = xgb_weight.predict(
        X_val_selected
    )


    # MODEL 2: XGBoost + SMOTE


    smote = SMOTE(
        random_state=42,
        k_neighbors=5
    )

    X_tr_smote, y_tr_smote = smote.fit_resample(
        X_tr_selected,
        y_tr
    )

    xgb_smote_fold = XGBClassifier(
        n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective='binary:logistic',
        eval_metric='logloss',
        random_state=42,
        n_jobs=-1
    )

    xgb_smote_fold.fit(
        X_tr_smote,
        y_tr_smote
    )

    pred_smote = xgb_smote_fold.predict(
        X_val_selected
    )


    # Metrics


    recall_weight = recall_score(
        y_val,
        pred_weight,
        pos_label=0,
        zero_division=0
    )

    precision_weight = precision_score(
        y_val,
        pred_weight,
        pos_label=0,
        zero_division=0
    )

    f1_weight = f1_score(
        y_val,
        pred_weight,
        pos_label=0,
        zero_division=0
    )

    recall_smote = recall_score(
        y_val,
        pred_smote,
        pos_label=0,
        zero_division=0
    )

    precision_smote = precision_score(
        y_val,
        pred_smote,
        pos_label=0,
        zero_division=0
    )

    f1_smote = f1_score(
        y_val,
        pred_smote,
        pos_label=0,
        zero_division=0
    )

    # Store predictions for overall confusion matrices


    all_y_true.extend(y_val.tolist())
    all_pred_weight.extend(pred_weight.tolist())
    all_pred_smote.extend(pred_smote.tolist())

    results.append({
        'segment_id': val_segment,
        'windows': len(y_val),

        'weight_precision_0': precision_weight,
        'weight_recall_0': recall_weight,
        'weight_f1_0': f1_weight,

        'smote_precision_0': precision_smote,
        'smote_recall_0': recall_smote,
        'smote_f1_0': f1_smote
    })

    print("Validation windows:", len(y_val))

    print(
        f"Class-weight XGB → "
        f"Precision: {precision_weight:.4f}, "
        f"Recall: {recall_weight:.4f}, "
        f"F1: {f1_weight:.4f}"
    )

    print(
        f"SMOTE XGB → "
        f"Precision: {precision_smote:.4f}, "
        f"Recall: {recall_smote:.4f}, "
        f"F1: {f1_smote:.4f}"
    )


# Results table

results_df = pd.DataFrame(results)

print("\n\n")
print("=" * 80)
print("UNSEEN ACTIVITY-0 SEGMENT RESULTS")
print("=" * 80)

print(
    results_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


# Average performance

print("\n\nAverage Activity-0 metrics:")
print("-" * 60)

print("\nXGBoost + Class Weight")
print(
    "Precision:",
    round(results_df['weight_precision_0'].mean(), 4)
)
print(
    "Recall:",
    round(results_df['weight_recall_0'].mean(), 4)
)
print(
    "F1:",
    round(results_df['weight_f1_0'].mean(), 4)
)

print("\nXGBoost + SMOTE")
print(
    "Precision:",
    round(results_df['smote_precision_0'].mean(), 4)
)
print(
    "Recall:",
    round(results_df['smote_recall_0'].mean(), 4)
)
print(
    "F1:",
    round(results_df['smote_f1_0'].mean(), 4)
)


# Overall confusion matrices

print("\n\nOverall confusion matrix:")
print("XGBoost + Class Weight")
print(
    confusion_matrix(
        all_y_true,
        all_pred_weight
    )
)

print("\nXGBoost + SMOTE")
print(
    confusion_matrix(
        all_y_true,
        all_pred_smote
    )
)


# Overall Activity-0 metrics


print("\nOverall Activity-0 performance:")

print("\nXGBoost + Class Weight")
print(
    "Precision:",
    round(
        precision_score(
            all_y_true,
            all_pred_weight,
            pos_label=0,
            zero_division=0
        ),
        4
    )
)
print(
    "Recall:",
    round(
        recall_score(
            all_y_true,
            all_pred_weight,
            pos_label=0,
            zero_division=0
        ),
        4
    )
)
print(
    "F1:",
    round(
        f1_score(
            all_y_true,
            all_pred_weight,
            pos_label=0,
            zero_division=0
        ),
        4
    )
)

print("\nXGBoost + SMOTE")
print(
    "Precision:",
    round(
        precision_score(
            all_y_true,
            all_pred_smote,
            pos_label=0,
            zero_division=0
        ),
        4
    )
)
print(
    "Recall:",
    round(
        recall_score(
            all_y_true,
            all_pred_smote,
            pos_label=0,
            zero_division=0
        ),
        4
    )
)
print(
    "F1:",
    round(
        f1_score(
            all_y_true,
            all_pred_smote,
            pos_label=0,
            zero_division=0
        ),
        4
    )
)

# The model performs very well on a leakage-safe segment-level holdout, with XGBoost achieving 72.7% F1 for standing.
# However, when evaluated on completely unseen standing episodes, recall dropped to about 23.8%.
# This showed that the main limitation is not only class imbalance but the lack of diverse independent standing data.
# Therefore, the model is a strong baseline, but more representative data collection is
# # required for reliable real-world generalization